name: Build App
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.19.0

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: 🏗 Setup EAS local builds
        run: npm i -g eas-cli-local-build-plugin

      - name: 📦 Install dependencies
        run: npm install
      - name: Generate Native Directories (if not committed)
        run: npx expo prebuild --clean
      - name: Build Android Release APK
        run: cd src/apps/native/android && ./gradlew assembleRelease
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: src/apps/native/android/app/build/outputs/apk/release/app-release.apk

