name: Development Build Android

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install

      - name: Install Expo CLI
        run: pnpm add -g expo-cli
      - name: Expo Prebuild
        run: pnpm --filter native exec expo prebuild --clean --platform android

      - name: Build Android App
        run: |
          cd apps/native/android
          ./gradlew assembleDebug

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: apps/native/android/app/build/outputs/apk/debug/app-debug.apk

